[package]
name = "serde_to_v8"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1"
integer-encoding = "3.0.2"
wasm-bindgen = "0.2.63"
convert_case = "0.4.0"

[profile.release]
opt-level = "z"
